kind: pipeline
type: docker
name: simc

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: build
  image: archlinux:base-devel
  privileged: true
  commands:
  - pacman --noconfirm -Syyu cmake curl pkg-config clang neofetch
  - neofetch
  - mkdir build
  - cd build
  - cmake ../ -DBUILD_GUI=OFF
  - make -j12
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_key
    files: build/simc
  when:
    event: tag